/**
 * generated by Xtext 2.14.0.RC1
 */
package org.xtext.compiler.pascal.pascal;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>constant chr</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.compiler.pascal.pascal.PascalPackage#getconstant_chr()
 * @model
 * @generated
 */
public interface constant_chr extends constant
{
} // constant_chr
