/**
 * generated by Xtext 2.14.0.RC1
 */
package org.xtext.compiler.pascal.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>formal parameter list</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.compiler.pascal.pascal.PascalPackage#getformal_parameter_list()
 * @model
 * @generated
 */
public interface formal_parameter_list extends EObject
{
} // formal_parameter_list
