/**
 * generated by Xtext 2.15.0
 */
package org.xtext.compiler.pascal.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>structured type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.compiler.pascal.pascal.structured_type#getUnpacked <em>Unpacked</em>}</li>
 * </ul>
 *
 * @see org.xtext.compiler.pascal.pascal.PascalPackage#getstructured_type()
 * @model
 * @generated
 */
public interface structured_type extends EObject
{
  /**
   * Returns the value of the '<em><b>Unpacked</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unpacked</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unpacked</em>' containment reference.
   * @see #setUnpacked(unpacked_structured_type)
   * @see org.xtext.compiler.pascal.pascal.PascalPackage#getstructured_type_Unpacked()
   * @model containment="true"
   * @generated
   */
  unpacked_structured_type getUnpacked();

  /**
   * Sets the value of the '{@link org.xtext.compiler.pascal.pascal.structured_type#getUnpacked <em>Unpacked</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unpacked</em>' containment reference.
   * @see #getUnpacked()
   * @generated
   */
  void setUnpacked(unpacked_structured_type value);

} // structured_type
