/**
 * generated by Xtext 2.14.0.RC1
 */
package org.xtext.compiler.pascal.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>unlabelled statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.compiler.pascal.pascal.unlabelled_statement#getSimple <em>Simple</em>}</li>
 *   <li>{@link org.xtext.compiler.pascal.pascal.unlabelled_statement#getStructured <em>Structured</em>}</li>
 * </ul>
 *
 * @see org.xtext.compiler.pascal.pascal.PascalPackage#getunlabelled_statement()
 * @model
 * @generated
 */
public interface unlabelled_statement extends EObject
{
  /**
   * Returns the value of the '<em><b>Simple</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Simple</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simple</em>' containment reference.
   * @see #setSimple(simple_statement)
   * @see org.xtext.compiler.pascal.pascal.PascalPackage#getunlabelled_statement_Simple()
   * @model containment="true"
   * @generated
   */
  simple_statement getSimple();

  /**
   * Sets the value of the '{@link org.xtext.compiler.pascal.pascal.unlabelled_statement#getSimple <em>Simple</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Simple</em>' containment reference.
   * @see #getSimple()
   * @generated
   */
  void setSimple(simple_statement value);

  /**
   * Returns the value of the '<em><b>Structured</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Structured</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Structured</em>' attribute.
   * @see #setStructured(String)
   * @see org.xtext.compiler.pascal.pascal.PascalPackage#getunlabelled_statement_Structured()
   * @model
   * @generated
   */
  String getStructured();

  /**
   * Sets the value of the '{@link org.xtext.compiler.pascal.pascal.unlabelled_statement#getStructured <em>Structured</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Structured</em>' attribute.
   * @see #getStructured()
   * @generated
   */
  void setStructured(String value);

} // unlabelled_statement
