/**
 * generated by Xtext 2.15.0
 */
package org.xtext.compiler.pascal.pascal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>unsigned number</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.compiler.pascal.pascal.unsigned_number#getNumbers <em>Numbers</em>}</li>
 * </ul>
 *
 * @see org.xtext.compiler.pascal.pascal.PascalPackage#getunsigned_number()
 * @model
 * @generated
 */
public interface unsigned_number extends EObject
{
  /**
   * Returns the value of the '<em><b>Numbers</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Numbers</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Numbers</em>' attribute list.
   * @see org.xtext.compiler.pascal.pascal.PascalPackage#getunsigned_number_Numbers()
   * @model unique="false"
   * @generated
   */
  EList<String> getNumbers();

} // unsigned_number
