/**
 * generated by Xtext 2.15.0
 */
package org.xtext.compiler.pascal.pascal.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.compiler.pascal.pascal.PascalPackage;
import org.xtext.compiler.pascal.pascal.constant;
import org.xtext.compiler.pascal.pascal.subrange_type;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>subrange type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.compiler.pascal.pascal.impl.subrange_typeImpl#getConstantInit <em>Constant Init</em>}</li>
 *   <li>{@link org.xtext.compiler.pascal.pascal.impl.subrange_typeImpl#getConstantFinal <em>Constant Final</em>}</li>
 * </ul>
 *
 * @generated
 */
public class subrange_typeImpl extends MinimalEObjectImpl.Container implements subrange_type
{
  /**
   * The cached value of the '{@link #getConstantInit() <em>Constant Init</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConstantInit()
   * @generated
   * @ordered
   */
  protected constant constantInit;

  /**
   * The cached value of the '{@link #getConstantFinal() <em>Constant Final</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConstantFinal()
   * @generated
   * @ordered
   */
  protected constant constantFinal;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected subrange_typeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PascalPackage.Literals.SUBRANGE_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public constant getConstantInit()
  {
    return constantInit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetConstantInit(constant newConstantInit, NotificationChain msgs)
  {
    constant oldConstantInit = constantInit;
    constantInit = newConstantInit;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PascalPackage.SUBRANGE_TYPE__CONSTANT_INIT, oldConstantInit, newConstantInit);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setConstantInit(constant newConstantInit)
  {
    if (newConstantInit != constantInit)
    {
      NotificationChain msgs = null;
      if (constantInit != null)
        msgs = ((InternalEObject)constantInit).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PascalPackage.SUBRANGE_TYPE__CONSTANT_INIT, null, msgs);
      if (newConstantInit != null)
        msgs = ((InternalEObject)newConstantInit).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PascalPackage.SUBRANGE_TYPE__CONSTANT_INIT, null, msgs);
      msgs = basicSetConstantInit(newConstantInit, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.SUBRANGE_TYPE__CONSTANT_INIT, newConstantInit, newConstantInit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public constant getConstantFinal()
  {
    return constantFinal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetConstantFinal(constant newConstantFinal, NotificationChain msgs)
  {
    constant oldConstantFinal = constantFinal;
    constantFinal = newConstantFinal;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PascalPackage.SUBRANGE_TYPE__CONSTANT_FINAL, oldConstantFinal, newConstantFinal);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setConstantFinal(constant newConstantFinal)
  {
    if (newConstantFinal != constantFinal)
    {
      NotificationChain msgs = null;
      if (constantFinal != null)
        msgs = ((InternalEObject)constantFinal).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PascalPackage.SUBRANGE_TYPE__CONSTANT_FINAL, null, msgs);
      if (newConstantFinal != null)
        msgs = ((InternalEObject)newConstantFinal).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PascalPackage.SUBRANGE_TYPE__CONSTANT_FINAL, null, msgs);
      msgs = basicSetConstantFinal(newConstantFinal, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PascalPackage.SUBRANGE_TYPE__CONSTANT_FINAL, newConstantFinal, newConstantFinal));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PascalPackage.SUBRANGE_TYPE__CONSTANT_INIT:
        return basicSetConstantInit(null, msgs);
      case PascalPackage.SUBRANGE_TYPE__CONSTANT_FINAL:
        return basicSetConstantFinal(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PascalPackage.SUBRANGE_TYPE__CONSTANT_INIT:
        return getConstantInit();
      case PascalPackage.SUBRANGE_TYPE__CONSTANT_FINAL:
        return getConstantFinal();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PascalPackage.SUBRANGE_TYPE__CONSTANT_INIT:
        setConstantInit((constant)newValue);
        return;
      case PascalPackage.SUBRANGE_TYPE__CONSTANT_FINAL:
        setConstantFinal((constant)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.SUBRANGE_TYPE__CONSTANT_INIT:
        setConstantInit((constant)null);
        return;
      case PascalPackage.SUBRANGE_TYPE__CONSTANT_FINAL:
        setConstantFinal((constant)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PascalPackage.SUBRANGE_TYPE__CONSTANT_INIT:
        return constantInit != null;
      case PascalPackage.SUBRANGE_TYPE__CONSTANT_FINAL:
        return constantFinal != null;
    }
    return super.eIsSet(featureID);
  }

} //subrange_typeImpl
