/**
 * generated by Xtext 2.15.0
 */
package org.xtext.compiler.pascal.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.compiler.pascal.ui.AbstractPascalUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PascalUiModule extends AbstractPascalUiModule {
  public PascalUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
