/*
 * generated by Xtext 2.14.0.RC1
 */
package org.xtext.compiler.pascal.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPascalScopeProvider extends DelegatingScopeProvider {
}
